comment:
  layout: "files"
  behavior: "default"

flags:
  admin:
    paths:
      - src/admin/**/*
    carryforward: false
  everything-else:
    ignore:
      - src/admin/**/*
    carryforward: false
