version = 1

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true
    [analyzers.meta]
    module_system = "es-modules"
    style_guide = "standard"
